= Changelog

All user facing changes are documented in this file.
For a developer/contributor oriented changelog, take a look at the link:https://codeberg.org/metio.wtf/ilo/commits/[commit history].

== link:https://codeberg.org/metio.wtf/ilo/compare/master...develop[Unreleased]

- nothing new yet

== link:https://codeberg.org/metio.wtf/ilo/compare/release/1.0.0...release/2.0.0[2.0.0]

- Allow to specify volumes using `--volume` (the project directory is still automatically mounted)
- Allow to specify labels using `--label`
- `--command` was removed in favor of positional parameters.
You can now just write `ilo some command here` instead of `ilo --command=some --command=command --command=here`.
- Allow to specify the name of the running container with `--name`
- The hostname of a running container is no longer set by default.
Set your own hostname with `--hostname` as before
- Add `--version` to show the installed version of `ilo`

== link:https://codeberg.org/metio.wtf/ilo/src/tag/1.0.0[1.0.0]

The first public release of `ilo`.
Therefore neither changes nor bugfixes, but rather an initial feature set, that seems to work fine (using podman) and is portable (as portable as podman/docker).

=== Features

- Start single container
- Specify which image to use
- Specify which command to run
- Persist those settings in .rc files
- Support podman/docker
