= Command Line Arguments

== Argument Files

In order to share the same options/commands across your team, `ilo` supports argument files which contain the options (like which image to use) for your project.
Create an empty text file and put all options in there with their corresponding values.
You can specify all options in a single line, separated by whitespace or use a new line for every option.
Use that argument file by calling `ilo @file-name`.
You can mix argument files with regular CLI options as well, e.g. `ilo shell --image=openjdk:latest @some-file`.
The argument file used by `ilo` developers can be seen link:../../build-env[here] and is used like this `ilo @build-env`

== List of arguments

In general, use `ilo --help` or `ilo COMMAND --help` in order to get help information provided by the `ilo` installation on your machine.

=== --help

Shows help information, either for `ilo` itself or one of its commands.

Used by:

* `ilo`
* `ilo shell`
* `ilo compose`

=== --version

Shows the version information for `ilo`.

Used by:

* `ilo`

=== --debug

Runs `ilo` in debug mode with extende output.
Use this for bug reports.

Used by:

* `ilo shell`
* `ilo compose`
