= Installation
:release-version: 2.3.0

Use the following locations in order to download the binary distribution of `ilo`:

* https://github.com/metio/ilo/releases
* https://bintray.com/metio/generic/ilo/
* https://codeberg.org/metio.wtf/ilo/releases

None of the widely used package managers have `ilo` in their repository yet.
In case you want to help package `ilo` for your preferred operating system, take a look at the link:https://codeberg.org/metio.wtf/ilo/issues?q=&type=all&sort=&state=open&labels=1361&milestone=0&assignee=0[open packaging issues].

== Package Types

=== Native Executable

This package does not require any Java runtime.
It has faster startup and lower memory consumption.
File size is a lot bigger compared to the Java based version.
It's currently only available for Unix based systems and uses the identifier `native-unix`.
It is created with link:https://www.graalvm.org/[GraalVM's] link:https://www.graalvm.org/docs/reference-manual/native-image/[native image] command.

=== Java 11 Runtime

This package requires a Java 11 runtime installed on the host machine.
It uses the identifier `java11`.

== Installation Methods

=== Manual Command Line (Mac/Linux)

[source,shell]
----
$ export ILO_VERSION={release-version}
$ export ILO_TYPE=native-unix # or java11
$ cd /path/to/ilo/installation/folder
$ curl --location https://github.com/metio/ilo/releases/download/${ILO_VERSION}/ilo-${ILO_VERSION}-${ILO_TYPE}.zip --output ilo.zip
$ curl --location https://github.com/metio/ilo/releases/download/${ILO_VERSION}/ilo-${ILO_VERSION}-${ILO_TYPE}.zip.minisig --output ilo.zip.minisig
$ minisign -Vm ilo.zip -P RWT6AkWGA/6Scei5KmcJ2WHk056ReUoHKi/+4kGvqy/i9Ogj173qrPU
$ unzip ilo.zip
$ ln --symbolic --relative ilo-${ILO_VERSION}/ilo /usr/local/bin/ilo
----

=== NixOS

[source,shell]
----
$ nix-env -i ilo
----

=== Windows

- Download https://github.com/metio/ilo/releases/download/{release-version}/ilo-{release-version}-java11.zip
- Extract it into a folder of your choice.
- Add `ilo.bat` to your `$PATH`

== CLI Autocomplete

In order to get autocomplete working in your shell, run the following after installing `ilo`:

[source,shell]
----
$ source <(ilo generate-completion)
----

Place the same line in your `.bashrc` (or similar) file in order to make the change permanent.

=== Oh-My-Zsh

OMZ uses the `$ZSH_CUSTOM` directory in order to customize your shell.
In order to integrate the autocomplete support, follow these steps:

1. Create a new file in `$ZSH_CUSTOM`, e.g. `$ZSH_CUSTOM/ilo.sh`.
2. Use the following template
+
[source,shell]
-----
source <(ilo generate-completion)
-----

3. Reload your shell (or create a new one)

