baseURL = "https://ilo.projects.metio.wtf/"
languageCode = "en"
theme = "metio"
title = "ilo"

pygmentsUseClasses = true
sectionPagesMenu = "main"
enableRobotsTXT = true
defaultContentLanguage = "en"
enableInlineShortcodes = true

[outputs]
  home = [ "HTML", "RSS", "ATOM", "HUMANS", "FOAF"]
  section = ["HTML", "RSS", "ATOM"]
  term = ["HTML", "RSS", "ATOM"]

[params]
  mainSections = ["community", "contributors", "integration", "metrics", "shell", "usage"]
  author = "metio.wtf"
  email = "https://metio.groups.io/g/main/topics"
  matrix = "#talk.metio:matrix.org"
  github = "metio/ilo"
  work = "ilo.projects.metio.wtf"
  description = "manage reproducible build environments"

[security.funcs]
  getenv = ['^HUGO_', '^ILO_']
